apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgclass
spec:
  replicas: 2
  selector:
    matchLabels:
      app: imageclassifier
  template:
    metadata:
      labels:
        app: imageclassifier
    spec:
      containers:
      - name: cv-app
        image: gcr.io/majorproject789/imgwebapp2 :v3
        ports:
        - containerPort: 8501
